# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0016_alter_model_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='default_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_owner', to=settings.AUTH_USER_MODEL, verbose_name='Default owner'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.IntegerField(choices=[(1, 'Issue / Bug'), (2, 'Enhancement'), (3, 'New Feature'), (4, 'Task / To Do'), (5, 'Training'), (6, 'Comments / Feedback')], default=1, verbose_name='Ticket Type'),
        ),
    ]
